databases:
  - name: instabot-db
    plan: free

services:
  - type: web
    name: instabot-worker
    env: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: instabot-db
          property: connectionString
      # Quyidagi o'zgaruvchilarni Render panelida kiritishingiz kerak bo'ladi
      - key: BOT_TOKEN
        sync: false
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: MAX_FILE_SIZE_MB
        value: "50"
